### ISSUE TITLE
[enhancement] regarding keybinding and monitor options in hyprgui

### ISSUE THREAD

**Issue by emm-enn** [nnyyxxxx/hyprgui#17]
hey! so i just installed your dots using the script and I have to say, they look very cool, the only thing is that the keybindings are kinda weird for me, it would be nice if hyprgui had options for that, thanks!

**Comment by adamperkowski** [comment]
We know. We'll be working on that sometime in the future. HyprGUI is only about 2 days old.

**Comment by adamperkowski** [comment]
> oh didn't know that it was this new, sorry for the issue lol.. are you guys part of axyl os? will this be in it ootb?

We've been invited to work with them. It's going to be bundled with the next release, according to @awfixer. See *Axyl Community* on Discord.

**Comment by nnyyxxxx** [comment]
this will be done at a much later date
